version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8443:8443'
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 27017
      DB_USER: BenoitZel
      DB_PASSWORD: KKH4WbxP77OVpmb4
      DB_NAME: clusterO

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  database:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: BenoitZel
      MONGO_INITDB_ROOT_PASSWORD: KKH4WbxP77OVpmb4
